#+TITLE:	README for Org Tree Slide
#+AUTHOR:	Takaaki Ishikawa
#+EMAIL:	takaxp@ieee.org
#+STARTUP:	content

* 1. What's this

The main purpose of this elisp is to handle each tree in a org buffer as a slide by simple narrowing. This emacs lisp is a minor mode for Emacs Org-mode. 

Main features:

  - Live editable presentation
  - Fast switching of narrowing/widen
  - TODO pursuit with narrowing
  - Displaying the current number of slides
  - Countdown timer
  - CONTENT view during a presentation
  - Slide in effect
  - Slide header from org file's header

** 1-1. Related packages

see [[http://orgmode.org/worg/org-tutorials/non-beamer-presentations.html]].

* 2. Install

1. Put this elisp into your load-path
2. Add =(require 'org-tree-slide)= in your =.emacs=

OR

1. Eval: =(auto-install-from-url "https://raw.github.com/takaxp/org-tree-slide/master/org-tree-slide.el")= (for auto-install user)
2. Add =(require 'org-tree-slide)= in your =.emacs=

Then open an org file, just type =<right>= and =<left>=. An presentation will begin with a header, slide-in effect, and slide number.

** 2.1 Requirements
  - Org-mode 6.33x or higher version is required.
  - This elisp doesn't require any additional packages.
* 3. Recommended settings

Assigning a single key to =org-tree-slide-mode= is recommended.

#+begin_src emacs lisp
(global-set-key (kbd "<f8>") 'org-tree-slide-mode)
(global-set-key (kbd "S-<f8>") 'org-tree-slide-skip-done-toggle)
#+end_src

OR

#+begin_src emacs lisp
(define-key org-mode-map (kbd "<f8>") 'org-tree-slide-mode)
(define-key org-mode-map (kbd "S-<f8>") 'org-tree-slide-skip-done-toggle)
#+end_src


* 4. Profiles

Three useful profiles are available. Please select a profile which is the most suitable for your useing scenario.

If you select =simple= profile, call the following command while =org-tree-slide-mode= is ON.

#+begin_src emacs lisp
M-x org-tree-slide-simple-profile
#+end_src

If you want to use this setting as the default, put the following configuration including recommended settings into your =.emacs=.

#+begin_src emacs lisp
(when (require 'org-tree-slide nil t)
  (global-set-key (kbd "<f8>") 'org-tree-slide-mode)
  (global-set-key (kbd "S-<f8>") 'org-tree-slide-skip-done-toggle)
  (org-tree-slide-simple-profile))
#+end_src

=org-tree-slide-presentation-profile= and =org-tree-slide-narrowing-control-profile= are also available.

** 4-1. `Simple'

This profile will display trees of your org buffer by simple narrowing. You can change trees without =widen= command. Most of the visual effect is disabled.

Type =M-x org-tree-slide-simple-profile= while =org-tree-slide-mode= is ON.

    1. No header display
    2. No slide-in effect
    3. The cursor will move to the head of the buffer when exit
    4. No slide number display in mode line
    5. Display every type of tree

** 4-2. `Presentation'

This profile is used as the default setting of org-tree-slide. If an org buffer includes =#+TITLE:=, =#+EMAIL:=, and =#+AUTHOR:=, org-tree-slide attempts to use those varialbes in the slide header. A date in the header will be set with the presentation of the day. You can enjoy a slide-in effect, the current slide number in mode line. A presentation with a count down timer is started by =M-x org-tree-slide-play-with-timer=.

If you want to show the content of your presentatison, type =C-x s r= or =M-x org-tree-slide-content=. All of the headers will be shown like a Table Of Content. Find a heading that you want to show, and type =<rihgt>=, the presentation will be resumed.

To exit a presentation, set =org-tree-slide-mode= OFF. The cursor move to the head of the buffer and trees will be displayed using =#+STARTUP:= if possible.

=M-x org-tree-slide-presentation-profile=

    1. Display header
    2. Enable slide-in effect
    3. The cursor will move to the head of buffer when exit
    4. Display slide number in mode line
    5. Display every type of tree

** 4-3. `TODO Pursuit with narrowing'

This profile will display trees restricted to =TODO status= without a header and slide-in effect. It is very useful to concentrate your focus on the current TODO item which is not done, and go to the next task by a single typing of =<right>=. This is "TODO Pursuit with narrowing". If you want to track every kind of tree including finished items, toggle =M-x org-tree-slide-skip-done= OFF.

When you exit =org-tree-slide-mode=, the cursor will keep the same position, it is therfore possible to focus again by toggle =M-x org-tree-slide-mode= again.

=M-x org-tree-slide-narrowing-control-profile=

    1. No header display
    2. No slide-in effect
    3. The cursor will keep the same position when exit
    4. Display slide number in mode line
    5. Display TODO trees only

* 5. User variables

|---+-------------------------------------+---------------+---------|
|   | Variable                            | Default value | Select  |
|---+-------------------------------------+---------------+---------|
| 1 | org-tree-slide-skip-outline-level   | 0             | numeric |
| 2 | org-tree-slide-header               | t             | boolean |
| 3 | org-tree-slide-slide-in-effect      | t             | boolean |
| 4 | org-tree-slide-slide-in-brank-lines | 10            | numeric |
| 5 | org-tree-slide-slide-in-waiting     | 0.02          | float   |
| 6 | org-tree-slide-cursor-init          | t             | boolean |
| 7 | org-tree-slide-heading-emphasis     | nil           | boolean |
| 8 | org-tree-slide-skip-done            | nil           | boolean |
| 9 | org-tree-slide-modeline-display     | 'outside      | [*1]    |
|---+-------------------------------------+---------------+---------|

#+begin_src org
[*1] ={ nil| 'lighter | 'outside }=
   'outside: shown in the mode line outside of lighter
   'lighter: shown in lighter (slow)
   nil: nothing to be shown"
#+end_src

* 6. History

see also ChangeLog

|---------+------------------+-----------------------------------------------|
| Version | Date             | Description                                   |
|---------+------------------+-----------------------------------------------|
| v2.5.1  | 2011-12-17@13:34 | org-tree-slide-skip-done set nil as default   |
| v2.5.0  | 2011-12-12@18:16 | Remove auto-play function (TBD)               |
| v2.4.1  | 2011-12-09@11:46 | Add an option to control mode line display    |
| v2.4.0  | 2011-12-08@10:51 | Support TODO pursuit in a slideshow           |
| v2.3.2  | 2011-12-08@09:22 | Reduce redundant processing                   |
| v2.3.1  | 2011-12-07@20:30 | Add a new profile to control narrowing status |
| v2.3.0  | 2011-12-07@16:17 | Support displaying a slide number             |
| v2.2.0  | 2011-12-07@02:15 | Support minor mode                            |
| v2.1.7  | 2011-12-06@00:26 | Support TITLE/AUTHOR/EMAIL in a header        |
| v2.1.5  | 2011-12-05@17:08 | Fix an issue of title display                 |
| v2.1.3  | 2011-12-05@15:08 | Fix the end of slide for skip control         |
| v2.1.1  | 2011-12-05@11:08 | Add skip control by heading level             |
| v2.0.1  | 2011-12-02@18:29 | Change function names, ots- is introduced.    |
| v2.0.0  | 2011-12-01@17:41 | Add profiles and support org 6.33x            |
| v1.2.5  | 2011-10-31@18:34 | Add CONTENT view to see all the subtrees.     |
| v1.2.3  | 2011-10-30@20:42 | Add a variable to control slide-in duration   |
| v1.2.1  | 2011-10-30@16:10 | Add slide-in visual effect                    |
| v1.1.1  | 2011-10-28@16:16 | Add functions to start and stop slide view    |
| v1.0.0  | 2011-09-28@20:59 | Release the initial version                   |
|---------+------------------+-----------------------------------------------|

* 7. Contact

The author is Takaaki ISHIKAWA (takaxp@ieee.org).
Feel free to email me or use a mention of twitter ([[https://twitter.com/#!/takaxp][@takaxp]])

